### ISSUE TITLE
Change default model to a free OpenAI model

### ISSUE THREAD

**Issue by hpatel292-seneca** [fadingNA/chat-completion-api#1]
The current code sets the default model to "gpt-4o", which is a paid model. Many users may not have access to this paid model. To improve accessibility for all users, please change the default model to a free option, such as "gpt-3.5-turbo".
![image](https://github.com/user-attachments/assets/2e6403e1-2d2c-467a-9121-4b4cfd756e85)

**Comment by fadingNA** [comment]
![Screenshot 2024-09-11 at 8 40 26 PM](https://github.com/user-attachments/assets/262d63ac-8544-4026-9f8e-449c5fd1e74d)

From 2024 OpenAI currently not offer any free models for chat completion, anyhow I will see what I can do to switch to another provider.
