### ISSUE TITLE
Suggestion: Addition of .DS_Store to .gitignore

### ISSUE THREAD

**Issue by Kannav02** [fadingNA/chat-completion-api#14]
Hey @fadingNA !

I just observed in your repo that while pushing folders/files to GitHub, your .DS_Store file is being pushed as well, this file may contain private meta-data which when exposed can lead to unauthorized access to your private data 

It's best here to add a statement in the .gitignore file to exclude .DS_Store from being pushed

P.S. to find more info about .DS_Store you can follow this [link](https://buildthis.com/ds_store-files-and-why-you-should-know-about-them/)

**Comment by fadingNA** [comment]
@Kannav02  Thank you for pointing this out will fix this now .

**Comment by fadingNA** [comment]
@Kannav02  

Closed [d7063a](https://github.com/fadingNA/chat-completion-api/commit/d7063a1947986b5842b367b9791242bb3509f8f7)
