### ISSUE TITLE
Add support for TOML config file

### ISSUE THREAD

**Issue by Elisassa** [fadingNA/chat-completion-api#15]
Enable reading configuration from a TOML file in the home directory to simplify tool setup.

**Comment by fadingNA** [comment]
ok

**Comment by fadingNA** [comment]
@Elisassa  can you make another PR i merged by mistake and your code not pass flake8 Run 
flake8 ./app/*.py
./app/config.py:3:13: W291 trailing whitespace
./app/config.py:31:1: E302 expected 2 blank lines, found 1
./app/config.py:42:1: E305 expected 2 blank lines after class or function definition, found 1
./app/config.py:4[8](https://github.com/fadingNA/chat-completion-api/actions/runs/11186595353/job/31101932442#step:5:9):1: W293 blank line contains whitespace
