### ISSUE TITLE
-o flag not working for output file, but --output works

### ISSUE THREAD

**Issue by hpatel292-seneca** [fadingNA/chat-completion-api#2]
The --output flag works correctly to save the generated completion to a file, but the shorthand version -o does not function as expected. The -o flag should also save the output to the specified file, but it currently does not.
 
 **Expected Behavior**: The -o flag should function the same as the --output flag, saving the output to the specified file.
**Actual Behavior**: The -o flag does not save the output to the specified file.

**Comment by fadingNA** [comment]
Incorrect if condition variable checking change output to output_file
<img width="1467" alt="Screenshot 2024-09-11 at 2 20 58 PM" src="https://github.com/user-attachments/assets/e2681277-6c4a-4ffd-bb58-94bed55eb58a">


Remove duplicate parameter on chat completiong
<img width="1446" alt="Screenshot 2024-09-11 at 2 21 18 PM" src="https://github.com/user-attachments/assets/1b06d442-24eb-41cf-9bfe-db2a40eab43a">
