### ISSUE TITLE
ChatPromptTemplate Expected a Mapping but Received a List in get_completion Function

### ISSUE THREAD

**Issue by hpatel292-seneca** [fadingNA/chat-completion-api#3]
**Description**: Running the sample usage results in the following error:

```bash
Error: 2024-09-11 14:21:17,120 | ERROR | Error in get_completion at line 189: Expected mapping type as input to ChatPromptTemplate. Received <class 'list'>.

```

**Comment by fadingNA** [comment]
![Screenshot 2024-09-11 at 8 37 21 PM](https://github.com/user-attachments/assets/890d7c73-7406-4d69-bdcf-8e72613f3a65)

add check input type instance always str prevent unbehaviour error

**Comment by fadingNA** [comment]
![Screenshot 2024-09-11 at 8 37 12 PM](https://github.com/user-attachments/assets/e72d040d-0bd3-4ab8-a78e-632280b0cdd2)

add type checking for input and context prevent add list into msg history
