### ISSUE TITLE
Error Reading Input File Due to Character Encoding Issue

### ISSUE THREAD

**Issue by hpatel292-seneca** [fadingNA/chat-completion-api#4]
**Description**: While attempting to read the input file (examples/computer_vision.txt), the following error occurs:

```bash
Error reading file examples/computer_vision.txt at line 97: 'charmap' codec can't decode byte 0x9d in position 2174: character maps to <undefined>
```
![image](https://github.com/user-attachments/assets/77dde141-2af8-4eed-9707-ada36d481fa2)

**Comment by fadingNA** [comment]
Fix error using utf-8 for unicode the character 

![Screenshot 2024-09-11 at 8 33 58 PM](https://github.com/user-attachments/assets/b0d0f61b-aea1-45e9-9c0b-56942de4daf6)
