### ISSUE TITLE
Using the tool without providing an api.

### ISSUE THREAD

**Issue by aldrin312** [fadingNA/chat-completion-api#6]
Using the program without providing an api key still prompts the user for a translation task.

![image](https://github.com/user-attachments/assets/4ca279bb-31d3-498c-9e5b-2a37d7a69e8d)

**Comment by fadingNA** [comment]
> Using the program without providing an api key still prompts the user for a translation task.
> 
> ![image](https://private-user-images.githubusercontent.com/28761163/367472315-4ca279bb-31d3-498c-9e5b-2a37d7a69e8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNzI3MTQsIm5iZiI6MTcyNjI3MjQxNCwicGF0aCI6Ii8yODc2MTE2My8zNjc0NzIzMTUtNGNhMjc5YmItMzFkMy00OThjLTllNWItMmEzN2Q3YTY5ZThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAwMDY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjZGVkZTQ3MTRkNThlZmY0ZjNmM2Q0NDI0N2M2OWIzNjBiMDg0NjIwM2UxMGI2ODg3OTEwOTA0ZmZhODAxN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xmzrkK0xCpCdR9138krFxOo6CN4ReiB1USs7f4X4myY)

That my not be possible because every provider we need our own api to run the models
