### ISSUE TITLE
Exceeding api’s quota.

### ISSUE THREAD

**Issue by aldrin312** [fadingNA/chat-completion-api#7]
The tools goes beyond the api limit for the ones that has a low quota, especially for the ones that are free.

Suggestion: If possible lowering the quota so that it allows api with a quota limit.

![image](https://github.com/user-attachments/assets/3db9291e-07d9-4706-a1d6-bc6a8c4b9071)

**Comment by fadingNA** [comment]
> The tools goes beyond the api limit for the ones that has a low quota, especially for the ones that are free.
> 
> Suggestion: If possible lowering the quota so that it allows api with a quota limit.
> 
> ![image](https://private-user-images.githubusercontent.com/28761163/367472546-3db9291e-07d9-4706-a1d6-bc6a8c4b9071.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNzI3NTYsIm5iZiI6MTcyNjI3MjQ1NiwicGF0aCI6Ii8yODc2MTE2My8zNjc0NzI1NDYtM2RiOTI5MWUtMDdkOS00NzA2LWExZDYtYmM2YThjNGI5MDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAwMDczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNGNhZmMwZmVmZGI1NzU2N2Y5MTUzYjIxNmM5ODE4NTY3NTBkYzk3YWI0ZjNiNmNmYzBlODI2ZjE2MTc0YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ojZHmiNim0cwRwhD8LjA3Yk_BZflePYz-4XmNz6bd4k)

I will change the provider that all of us can use a free api and run the model.

https://github.com/fadingNA/chat-completion-api/commit/42017cf486641ee60d9220a944791187f4491fd3

**Comment by fadingNA** [comment]
Change from OpenAI to Groq for free tier api usage

https://github.com/fadingNA/chat-completion-api/commit/bb7e8cf2f312d156c250b4e9fdab7fd3dd629d2c
