### ISSUE TITLE
Feat: chat completion token info flag option

### ISSUE THREAD

**Issue by cleobnvntra** [fadingNA/chat-completion-api#8]
# Description
A flag option that gives the user a count of tokens sent and received.
I think that it is an important feature that guides the user to stay within the token budget when making a chat completions request!

# Implementation
To do this, we would need to add another option flag which could be `-t` and `--token-usage`. When a user includes this flag to their command, it should display in clear detail how many tokens were used in the generation of the completion, and how many tokens were used in the prompt.

**Comment by fadingNA** [comment]
@cleobnvntra we can use -u and --token-usage , because I have -t for temperature already.

**Comment by cleobnvntra** [comment]
@fadingNA I tried to implement it using the `-u` flag, but found out that you are also using the `-u` flag for `--base-url`. Is there any other flag you suggest to use? I'm thinking of using `-tu` instead. Let me know what you think!

**Comment by fadingNA** [comment]
@cleobnvntra  you can use -k instead, 2 syllable might confilct with Linux command

**Comment by fadingNA** [comment]
@cleobnvntra  I tihnk just --token-usage that's fine

**Comment by cleobnvntra** [comment]
@fadingNA gotcha
